#  a lightweight Python image
FROM python:3.9-slim

# Installing the requests library for HTTP requests
RUN pip install requests

# Copy of the test script
COPY test_nginx.py /test_nginx.py

# Run of the test script
CMD ["python", "/test_nginx.py"]
