# Use Ubuntu as the base image
FROM ubuntu:latest

# Installing Nginx
RUN apt-get update && \
    apt-get install -y nginx && \
    rm -rf /var/lib/apt/lists/*

# Copy custom Nginx configuration
COPY nginx.conf /etc/nginx/nginx.conf

#  ports for the two servers
EXPOSE 8080 8081

# Start Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]
