name: CI Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and Test Containers
      run: |
        echo "Starting Build and Test Containers"
        
        # docker compose
        docker compose -f docker-compose.yml up --build --abort-on-container-exit
        
        if [ $? -eq 0 ]; then
          echo "succeeded" > result.txt
          echo "Test passed: Both Nginx server blocks responded as expected." >> result.txt
          echo "- Server Block 1 on port 8080 returned a 200 OK response" >> result.txt
          echo "- Server Block 2 on port 8081 returned a 404 Not Found response" >> result.txt
        else
          echo "fail" > result.txt
          echo "Test failed: Nginx servers did not respond as expected." >> result.txt
        fi

    - name: Upload Result Artifact
      uses: actions/upload-artifact@v3
      with:
        name: test-result
        path: result.txt
