name: CI Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Start Timer
      run: echo "start-time=$(date +%s)" >> $GITHUB_ENV

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug - Check Docker Installation
      run: |
        start_time=$(date +%s)
        echo "Start Docker Installation Check at $start_time"
        docker --version
        end_time=$(date +%s)
        echo "Docker Installation Check took $((end_time - start_time)) seconds."

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and Test Containers
      run: |
        start_time=$(date +%s)
        echo "Starting Build and Test Containers at $start_time"
        
        # Run docker compose
        docker compose -f docker-compose.yml up --build --abort-on-container-exit
        
        if [ $? -eq 0 ]; then
          echo "succeeded" > result.txt
          echo "Test passed: Both Nginx server blocks responded as expected." >> result.txt
          echo "- Server Block 1 on port 8080 returned a 200 OK response" >> result.txt
          echo "- Server Block 2 on port 8081 returned a 404 Not Found response" >> result.txt
        else
          echo "fail" > result.txt
          echo "Test failed: Nginx servers did not respond as expected." >> result.txt
        fi
        
        end_time=$(date +%s)
        echo "Build and Test Containers took $((end_time - start_time)) seconds."

    - name: Upload Result Artifact
      uses: actions/upload-artifact@v3
      with:
        name: test-result
        path: result.txt

    - name: End Timer and Calculate Total Duration
      run: |
        start_time=$(( ${{ env.start-time }} ))
        end_time=$(date +%s)
        total_duration=$((end_time - start_time))
        echo "Total CI job duration: $total_duration seconds."
